title: "Train Smarter Not Harder"
name: "Benjamin Thorne"
description: "Notes, projects, and research thoughts"
url: "https://Benji916.github.io"
repository: "Benji916/Benji916.github.io"

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

author:
  name: "Benjamin Thorne"
